@IsTest 
global class SRPortalControllerExtensionTest{
   
    static testMethod void unitTest(){          
       // Test.startTest();
       // Call the method that invokes a callout
       // Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
       //String output1 = SRPortalControllerExtension.getDCAddressByLatitudeLongitude('38.905359','-77.043919');
       
       //String output2 = SRPortalControllerExtension.getMarylandStatePlanCoordinates('38.905359','-77.043919');
       //String output3 = SRPortalControllerExtension.reverseGeoCodeDCAddress('396190.582555534,137501.072983467');
       //String output4 =  SRPortalControllerExtension.getValueFromXMLString('<ConvStr>396190.582555534,137501.072983467</ConvStr>','ConvStr',0);
        
      /*  // Verify that a result is returned
        System.assertEquals('http://citizenatlas.dc.gov/usng/getusng.asmx/MD_LLtoSPCS?LATLONSTR=38.905359,-77.043919', output1); 
        System.assertEquals('http://citizenatlas.dc.gov/usng/getusng.asmx/MD_LLtoSPCS?LATLONSTR=38.905359,-77.043919', output2); 
        System.assertEquals('http://citizenatlas.dc.gov//newwebservices/locationverifier.asmx/reverseGeocoding2?x=396190.582555534&y=137501.072983467&f=xml', output3);*/ 
        //Test.stopTest();
    }      
}